GRID_WIDTH = 10
GRID_HEIGHT = 10

GRID_BOX_WIDTH = 50
GRID_BOX_HEIGHT = 50

WINDOWWIDTH = GRID_WIDTH * GRID_BOX_WIDTH
WINDOWHEIGHT = GRID_HEIGHT * GRID_BOX_HEIGHT

PLAYER_WIDTH = GRID_BOX_WIDTH - 4
PLAYER_HEIGHT = GRID_BOX_HEIGHT - 4

GRID_XCOORD_START = GRID_WIDTH / 2
GRID_YCOORD_START = GRID_HEIGHT / 2

FPS = 15

# Define some colors
#             R    G    B
WHITE     = (255, 255, 255)
BLACK     = (  0,   0,   0)
RED       = (255,   0,   0)
GREEN     = (  0, 255,   0)
DARKGREEN = (  0, 155,   0)
DARKGRAY  = ( 40,  40,  40)
BGCOLOR = BLACK

LEFT = 'left'
RIGHT = 'right'
UP = 'up'
DOWN = 'down'

GRAVITY = -5
SPEED = 10

